// clang-format off
#include <windows.h>
#include <sql.h>
#include <sqlext.h>
// clang-format on

#include <vector>

// macro to get string representation of a define
#define MAP_INFO(NAME, argType) {NAME, #NAME, argType}

enum class ParamType
{
   String,
   Int,
   Short,
   Unknown
};

struct InfotypeInfo
{
   unsigned infotype;
   const char *name;
   ParamType paramType;
};
namespace
{
std::vector<InfotypeInfo> infotypes = {
    MAP_INFO(SQL_MAX_DRIVER_CONNECTIONS, ParamType::String),
    MAP_INFO(SQL_MAX_CONCURRENT_ACTIVITIES, ParamType::String),
    MAP_INFO(SQL_DATA_SOURCE_NAME, ParamType::String),
    MAP_INFO(SQL_DRIVER_HDBC, ParamType::String),
    MAP_INFO(SQL_DRIVER_HENV, ParamType::String),
    MAP_INFO(SQL_DRIVER_HSTMT, ParamType::String),
    MAP_INFO(SQL_DRIVER_NAME, ParamType::String),
    MAP_INFO(SQL_DRIVER_VER, ParamType::String),
    MAP_INFO(SQL_FETCH_DIRECTION, ParamType::String),
    MAP_INFO(SQL_ODBC_API_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_ODBC_VER, ParamType::String),
    MAP_INFO(SQL_ROW_UPDATES, ParamType::String),
    MAP_INFO(SQL_ODBC_SAG_CLI_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_SERVER_NAME, ParamType::String),
    MAP_INFO(SQL_SEARCH_PATTERN_ESCAPE, ParamType::String),
    MAP_INFO(SQL_ODBC_SQL_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_DATABASE_NAME, ParamType::String),
    MAP_INFO(SQL_DBMS_NAME, ParamType::String),
    MAP_INFO(SQL_DBMS_VER, ParamType::String),
    MAP_INFO(SQL_ACCESSIBLE_TABLES, ParamType::String),
    MAP_INFO(SQL_ACCESSIBLE_PROCEDURES, ParamType::String),
    MAP_INFO(SQL_PROCEDURES, ParamType::String),
    MAP_INFO(SQL_CONCAT_NULL_BEHAVIOR, ParamType::String),
    MAP_INFO(SQL_CURSOR_COMMIT_BEHAVIOR, ParamType::String),
    MAP_INFO(SQL_CURSOR_ROLLBACK_BEHAVIOR, ParamType::String),
    MAP_INFO(SQL_DATA_SOURCE_READ_ONLY, ParamType::String),
    MAP_INFO(SQL_DEFAULT_TXN_ISOLATION, ParamType::String),
    MAP_INFO(SQL_EXPRESSIONS_IN_ORDERBY, ParamType::String),
    MAP_INFO(SQL_IDENTIFIER_CASE, ParamType::String),
    MAP_INFO(SQL_IDENTIFIER_QUOTE_CHAR, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMN_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_CURSOR_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_SCHEMA_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_PROCEDURE_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_CATALOG_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_TABLE_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MULT_RESULT_SETS, ParamType::String),
    MAP_INFO(SQL_MULTIPLE_ACTIVE_TXN, ParamType::String),
    MAP_INFO(SQL_OUTER_JOINS, ParamType::String),
    MAP_INFO(SQL_OWNER_TERM, ParamType::String),
    MAP_INFO(SQL_PROCEDURE_TERM, ParamType::String),
    MAP_INFO(SQL_QUALIFIER_NAME_SEPARATOR, ParamType::String),
    MAP_INFO(SQL_QUALIFIER_TERM, ParamType::String),
    MAP_INFO(SQL_SCROLL_CONCURRENCY, ParamType::String),
    MAP_INFO(SQL_SCROLL_OPTIONS, ParamType::String),
    MAP_INFO(SQL_TABLE_TERM, ParamType::String),
    MAP_INFO(SQL_TXN_CAPABLE, ParamType::String),
    MAP_INFO(SQL_USER_NAME, ParamType::String),
    MAP_INFO(SQL_CONVERT_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_NUMERIC_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_STRING_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_SYSTEM_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_TIMEDATE_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_CONVERT_BIGINT, ParamType::String),
    MAP_INFO(SQL_CONVERT_BINARY, ParamType::String),
    MAP_INFO(SQL_CONVERT_BIT, ParamType::String),
    MAP_INFO(SQL_CONVERT_CHAR, ParamType::String),
    MAP_INFO(SQL_CONVERT_DATE, ParamType::String),
    MAP_INFO(SQL_CONVERT_DECIMAL, ParamType::String),
    MAP_INFO(SQL_CONVERT_DOUBLE, ParamType::String),
    MAP_INFO(SQL_CONVERT_FLOAT, ParamType::String),
    MAP_INFO(SQL_CONVERT_INTEGER, ParamType::String),
    MAP_INFO(SQL_CONVERT_LONGVARCHAR, ParamType::String),
    MAP_INFO(SQL_CONVERT_NUMERIC, ParamType::String),
    MAP_INFO(SQL_CONVERT_REAL, ParamType::String),
    MAP_INFO(SQL_CONVERT_SMALLINT, ParamType::String),
    MAP_INFO(SQL_CONVERT_TIME, ParamType::String),
    MAP_INFO(SQL_CONVERT_TIMESTAMP, ParamType::String),
    MAP_INFO(SQL_CONVERT_TINYINT, ParamType::String),
    MAP_INFO(SQL_CONVERT_VARBINARY, ParamType::String),
    MAP_INFO(SQL_CONVERT_VARCHAR, ParamType::String),
    MAP_INFO(SQL_CONVERT_LONGVARBINARY, ParamType::String),
    MAP_INFO(SQL_TXN_ISOLATION_OPTION, ParamType::String),
    MAP_INFO(SQL_INTEGRITY, ParamType::String),
    MAP_INFO(SQL_CORRELATION_NAME, ParamType::String),
    MAP_INFO(SQL_NON_NULLABLE_COLUMNS, ParamType::String),
    MAP_INFO(SQL_DRIVER_HLIB, ParamType::String),
    MAP_INFO(SQL_DRIVER_ODBC_VER, ParamType::String),
    MAP_INFO(SQL_LOCK_TYPES, ParamType::String),
    MAP_INFO(SQL_POS_OPERATIONS, ParamType::String),
    MAP_INFO(SQL_POSITIONED_STATEMENTS, ParamType::String),
    MAP_INFO(SQL_GETDATA_EXTENSIONS, ParamType::String),
    MAP_INFO(SQL_BOOKMARK_PERSISTENCE, ParamType::String),
    MAP_INFO(SQL_STATIC_SENSITIVITY, ParamType::String),
    MAP_INFO(SQL_FILE_USAGE, ParamType::String),
    MAP_INFO(SQL_NULL_COLLATION, ParamType::String),
    MAP_INFO(SQL_ALTER_TABLE, ParamType::String),
    MAP_INFO(SQL_COLUMN_ALIAS, ParamType::String),
    MAP_INFO(SQL_GROUP_BY, ParamType::String),
    MAP_INFO(SQL_KEYWORDS, ParamType::String),
    MAP_INFO(SQL_ORDER_BY_COLUMNS_IN_SELECT, ParamType::String),
    MAP_INFO(SQL_OWNER_USAGE, ParamType::String),
    MAP_INFO(SQL_QUALIFIER_USAGE, ParamType::String),
    MAP_INFO(SQL_QUOTED_IDENTIFIER_CASE, ParamType::String),
    MAP_INFO(SQL_SPECIAL_CHARACTERS, ParamType::String),
    MAP_INFO(SQL_SUBQUERIES, ParamType::String),
    MAP_INFO(SQL_UNION, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMNS_IN_GROUP_BY, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMNS_IN_INDEX, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMNS_IN_ORDER_BY, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMNS_IN_SELECT, ParamType::String),
    MAP_INFO(SQL_MAX_COLUMNS_IN_TABLE, ParamType::String),
    MAP_INFO(SQL_MAX_INDEX_SIZE, ParamType::String),
    MAP_INFO(SQL_MAX_ROW_SIZE_INCLUDES_LONG, ParamType::String),
    MAP_INFO(SQL_MAX_ROW_SIZE, ParamType::String),
    MAP_INFO(SQL_MAX_STATEMENT_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_TABLES_IN_SELECT, ParamType::String),
    MAP_INFO(SQL_MAX_USER_NAME_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_CHAR_LITERAL_LEN, ParamType::String),
    MAP_INFO(SQL_TIMEDATE_ADD_INTERVALS, ParamType::String),
    MAP_INFO(SQL_TIMEDATE_DIFF_INTERVALS, ParamType::String),
    MAP_INFO(SQL_NEED_LONG_DATA_LEN, ParamType::String),
    MAP_INFO(SQL_MAX_BINARY_LITERAL_LEN, ParamType::String),
    MAP_INFO(SQL_LIKE_ESCAPE_CLAUSE, ParamType::String),
    MAP_INFO(SQL_QUALIFIER_LOCATION, ParamType::String),
    MAP_INFO(SQL_OJ_CAPABILITIES, ParamType::String),
    MAP_INFO(SQL_ACTIVE_ENVIRONMENTS, ParamType::String),
    MAP_INFO(SQL_ALTER_DOMAIN, ParamType::String),
    MAP_INFO(SQL_SQL_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_DATETIME_LITERALS, ParamType::String),
    MAP_INFO(SQL_BATCH_ROW_COUNT, ParamType::String),
    MAP_INFO(SQL_BATCH_SUPPORT, ParamType::String),
    MAP_INFO(SQL_CONVERT_WCHAR, ParamType::String),
    MAP_INFO(SQL_CONVERT_INTERVAL_DAY_TIME, ParamType::String),
    MAP_INFO(SQL_CONVERT_INTERVAL_YEAR_MONTH, ParamType::String),
    MAP_INFO(SQL_CONVERT_WLONGVARCHAR, ParamType::String),
    MAP_INFO(SQL_CONVERT_WVARCHAR, ParamType::String),
    MAP_INFO(SQL_CREATE_ASSERTION, ParamType::String),
    MAP_INFO(SQL_CREATE_CHARACTER_SET, ParamType::String),
    MAP_INFO(SQL_CREATE_COLLATION, ParamType::String),
    MAP_INFO(SQL_CREATE_DOMAIN, ParamType::String),
    MAP_INFO(SQL_CREATE_SCHEMA, ParamType::String),
    MAP_INFO(SQL_CREATE_TABLE, ParamType::String),
    MAP_INFO(SQL_CREATE_TRANSLATION, ParamType::String),
    MAP_INFO(SQL_CREATE_VIEW, ParamType::String),
    MAP_INFO(SQL_DRIVER_HDESC, ParamType::String),
    MAP_INFO(SQL_DROP_ASSERTION, ParamType::String),
    MAP_INFO(SQL_DROP_CHARACTER_SET, ParamType::String),
    MAP_INFO(SQL_DROP_COLLATION, ParamType::String),
    MAP_INFO(SQL_DROP_DOMAIN, ParamType::String),
    MAP_INFO(SQL_DROP_SCHEMA, ParamType::String),
    MAP_INFO(SQL_DROP_TABLE, ParamType::String),
    MAP_INFO(SQL_DROP_TRANSLATION, ParamType::String),
    MAP_INFO(SQL_DROP_VIEW, ParamType::String),
    MAP_INFO(SQL_DYNAMIC_CURSOR_ATTRIBUTES1, ParamType::String),
    MAP_INFO(SQL_DYNAMIC_CURSOR_ATTRIBUTES2, ParamType::String),
    MAP_INFO(SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1, ParamType::String),
    MAP_INFO(SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2, ParamType::String),
    MAP_INFO(SQL_INDEX_KEYWORDS, ParamType::String),
    MAP_INFO(SQL_INFO_SCHEMA_VIEWS, ParamType::String),
    MAP_INFO(SQL_KEYSET_CURSOR_ATTRIBUTES1, ParamType::String),
    MAP_INFO(SQL_KEYSET_CURSOR_ATTRIBUTES2, ParamType::String),
    MAP_INFO(SQL_ODBC_INTERFACE_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_PARAM_ARRAY_ROW_COUNTS, ParamType::String),
    MAP_INFO(SQL_PARAM_ARRAY_SELECTS, ParamType::String),
    MAP_INFO(SQL_SQL92_DATETIME_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_SQL92_FOREIGN_KEY_DELETE_RULE, ParamType::String),
    MAP_INFO(SQL_SQL92_FOREIGN_KEY_UPDATE_RULE, ParamType::String),
    MAP_INFO(SQL_SQL92_GRANT, ParamType::String),
    MAP_INFO(SQL_SQL92_NUMERIC_VALUE_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_SQL92_PREDICATES, ParamType::String),
    MAP_INFO(SQL_SQL92_RELATIONAL_JOIN_OPERATORS, ParamType::String),
    MAP_INFO(SQL_SQL92_REVOKE, ParamType::String),
    MAP_INFO(SQL_SQL92_ROW_VALUE_CONSTRUCTOR, ParamType::String),
    MAP_INFO(SQL_SQL92_STRING_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_SQL92_VALUE_EXPRESSIONS, ParamType::String),
    MAP_INFO(SQL_STANDARD_CLI_CONFORMANCE, ParamType::String),
    MAP_INFO(SQL_STATIC_CURSOR_ATTRIBUTES1, ParamType::String),
    MAP_INFO(SQL_STATIC_CURSOR_ATTRIBUTES2, ParamType::String),
    MAP_INFO(SQL_AGGREGATE_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_DDL_INDEX, ParamType::String),
    MAP_INFO(SQL_DM_VER, ParamType::String),
    MAP_INFO(SQL_INSERT_STATEMENT, ParamType::String),
    MAP_INFO(SQL_CONVERT_GUID, ParamType::String),
    MAP_INFO(SQL_XOPEN_CLI_YEAR, ParamType::String),
    MAP_INFO(SQL_CURSOR_SENSITIVITY, ParamType::String),
    MAP_INFO(SQL_DESCRIBE_PARAMETER, ParamType::String),
    MAP_INFO(SQL_CATALOG_NAME, ParamType::String),
    MAP_INFO(SQL_COLLATION_SEQ, ParamType::String),
    MAP_INFO(SQL_MAX_IDENTIFIER_LEN, ParamType::String),
    MAP_INFO(SQL_ASYNC_MODE, ParamType::String),
    MAP_INFO(SQL_MAX_ASYNC_CONCURRENT_STATEMENTS, ParamType::String),
    MAP_INFO(SQL_ASYNC_DBC_FUNCTIONS, ParamType::String),
    MAP_INFO(SQL_DRIVER_AWARE_POOLING_SUPPORTED, ParamType::String),
    MAP_INFO(SQL_ASYNC_NOTIFICATION, ParamType::String),
};

}
InfotypeInfo GetInfoType(SQLUSMALLINT infotype)
{
   for (InfotypeInfo infoType : infotypes)
   {
      if (infoType.infotype == infotype)
      {
         return infoType;
      }
   }
   return InfotypeInfo{infotype, "Unknown", ParamType::Unknown};
}